from configparser import ConfigParser

config = ConfigParser()

config.read("settings.ini")

settings = {
    'token': config.get("BOT", "token"),
    'id': config.get("BOT", "clientid"),
    'adminid': config.get("BOT", "adminid"),
    'prefix': config.get("BOT", "prefix"),
    'status': config.get("BOT", "status"),
    'playing': config.get("BOT", "playing"),
}

language = config.get("LOCALE", "language")
section = language.upper()
config.read("locales/{}.ini".format(language))

lang = {
    'login': config.get(section, "login").encode('cp1251').decode('utf-8'),
    'prefix': config.get(section, "prefix").encode('cp1251').decode('utf-8'),
    'status': config.get(section, "status").encode('cp1251').decode('utf-8'),
    'playing': config.get(section, "playing").encode('cp1251').decode('utf-8'),
    'cogunload': config.get(section, "cogunload").encode('cp1251').decode('utf-8'),
    'cogload': config.get(section, "cogload").encode('cp1251').decode('utf-8'),
    'notenoughrights': config.get(section, "notenoughrights").encode('cp1251').decode('utf-8'),
    'cogreload': config.get(section, "cogreload").encode('cp1251').decode('utf-8'), 
    'congrats': config.get(section, "congrats").encode('cp1251').decode('utf-8'), 
    'lvlup': config.get(section, "lvlup").encode('cp1251').decode('utf-8'), 
    'notpoll': config.get(section, "notpoll").encode('cp1251').decode('utf-8'), 
    'newpoll': config.get(section, "newpoll").encode('cp1251').decode('utf-8'), 
    'pollgivenby': config.get(section, "pollgivenby").encode('cp1251').decode('utf-8'), 
    'hello': config.get(section, "hello").encode('cp1251').decode('utf-8'),
    'pong': config.get(section, "pong").encode('cp1251').decode('utf-8'),
    'shutdown': config.get(section, "shutdown").encode('cp1251').decode('utf-8'), 
    'latency': config.get(section, "latency").encode('cp1251').decode('utf-8'), 
    'response': config.get(section, "response").encode('cp1251').decode('utf-8'), 
    'avatar': config.get(section, "avatar").encode('cp1251').decode('utf-8'), 
    'fox': config.get(section, "fox").encode('cp1251').decode('utf-8'), 
    'cat': config.get(section, "cat").encode('cp1251').decode('utf-8'), 
    'kickby': config.get(section, "kickby").encode('cp1251').decode('utf-8'), 
    'banby': config.get(section, "banby").encode('cp1251').decode('utf-8'), 
    'unbanby': config.get(section, "unbanby").encode('cp1251').decode('utf-8'), 
    'msgdelete': config.get(section, "msgdelete").encode('cp1251').decode('utf-8'), 
    'errorblock': config.get(section, "errorblock").encode('cp1251').decode('utf-8'), 
    'cmdnotfound': config.get(section, "cmdnotfound").encode('cp1251').decode('utf-8'),
    'msgcmdnotfound': config.get(section, "msgcmdnotfound").encode('cp1251').decode('utf-8'),
    'slowmodeerror': config.get(section, "slowmodeerror").encode('cp1251').decode('utf-8'), 
    'msgslowmodeerror': config.get(section, "msgslowmodeerror").encode('cp1251').decode('utf-8'), 
    'missingpermissions': config.get(section, "missingpermissions").encode('cp1251').decode('utf-8'), 
    'msgmissingpermissions': config.get(section, "msgmissingpermissions").encode('cp1251').decode('utf-8'),
    'missingarguments': config.get(section, "missingarguments").encode('cp1251').decode('utf-8'), 
    'msgmissingarguments': config.get(section, "msgmissingarguments").encode('cp1251').decode('utf-8'), 
    'notvoice': config.get(section, "notvoice").encode('cp1251').decode('utf-8'),
    'msgnotvoice': config.get(section, "msgnotvoice").encode('cp1251').decode('utf-8'),
    'nowplaying': config.get(section, "nowplaying").encode('cp1251').decode('utf-8'),
    'duration': config.get(section, "duration").encode('cp1251').decode('utf-8'),
    'reqby': config.get(section, "reqby").encode('cp1251').decode('utf-8'),
    'uploader': config.get(section, "uploader").encode('cp1251').decode('utf-8'),
    'url': config.get(section, "url").encode('cp1251').decode('utf-8'),
    'track': config.get(section, "track").encode('cp1251').decode('utf-8'),
    'trackadded': config.get(section, "trackadded").encode('cp1251').decode('utf-8'),
    'togo': config.get(section, "togo").encode('cp1251').decode('utf-8'),
    'queue': config.get(section, "queue").encode('cp1251').decode('utf-8'),
    'notplaying': config.get(section, "notplaying").encode('cp1251').decode('utf-8'),
    'pause': config.get(section, "pause").encode('cp1251').decode('utf-8'),
    'resume': config.get(section, "resume").encode('cp1251').decode('utf-8'),
    'notconnected': config.get(section, "notconnected").encode('cp1251').decode('utf-8'),
    'skip': config.get(section, "skip").encode('cp1251').decode('utf-8'),
    'unloaddc': config.get(section, "unloaddc").encode('cp1251').decode('utf-8'),
    'unloadbrief': config.get(section, "unloadbrief").encode('cp1251').decode('utf-8'),
    'loaddc': config.get(section, "loaddc").encode('cp1251').decode('utf-8'),
    'loadbrief': config.get(section, "loadbrief").encode('cp1251').decode('utf-8'),
    'reloaddc': config.get(section, "reloaddc").encode('cp1251').decode('utf-8'),
    'reloadbrief': config.get(section, "reloadbrief").encode('cp1251').decode('utf-8'),
    'pongdc': config.get(section, "pongdc").encode('cp1251').decode('utf-8'),
    'avatardc': config.get(section, "avatardc").encode('cp1251').decode('utf-8'),
    'hellodc': config.get(section, "hellodc").encode('cp1251').decode('utf-8'),
    'saydc': config.get(section, "saydc").encode('cp1251').decode('utf-8'),
    'shutdowndc': config.get(section, "shutdowndc").encode('cp1251').decode('utf-8'),
    'rankdc': config.get(section, "rankdc").encode('cp1251').decode('utf-8'),
    'foxdc': config.get(section, "foxdc").encode('cp1251').decode('utf-8'),
    'foxbrief': config.get(section, "foxbrief").encode('cp1251').decode('utf-8'),
    'catdc': config.get(section, "catdc").encode('cp1251').decode('utf-8'),
    'catbrief': config.get(section, "catbrief").encode('cp1251').decode('utf-8'),
    'polldc': config.get(section, "polldc").encode('cp1251').decode('utf-8'),
    'playdc': config.get(section, "playdc").encode('cp1251').decode('utf-8'),
    'playbrief': config.get(section, "playbrief").encode('cp1251').decode('utf-8'),
    'queuedc': config.get(section, "queuedc").encode('cp1251').decode('utf-8'),
    'queuebrief': config.get(section, "queuebrief").encode('cp1251').decode('utf-8'),
    'pausedc': config.get(section, "pausedc").encode('cp1251').decode('utf-8'),
    'pausebrief': config.get(section, "pausebrief").encode('cp1251').decode('utf-8'),
    'skipdc': config.get(section, "skipdc").encode('cp1251').decode('utf-8'),
    'skipbrief': config.get(section, "skipbrief").encode('cp1251').decode('utf-8'),
    'kickdc': config.get(section, "kickdc").encode('cp1251').decode('utf-8'),
    'kickbrief': config.get(section, "kickbrief").encode('cp1251').decode('utf-8'),
    'bandc': config.get(section, "bandc").encode('cp1251').decode('utf-8'),
    'banbrief': config.get(section, "banbrief").encode('cp1251').decode('utf-8'),
    'unbandc': config.get(section, "unbandc").encode('cp1251').decode('utf-8'),
    'unbanbrief': config.get(section, "unbanbrief").encode('cp1251').decode('utf-8'),
    'noreason': config.get(section, "noreason").encode('cp1251').decode('utf-8'),
    'clearbrief': config.get(section, "clearbrief").encode('cp1251').decode('utf-8'),
    'cleardc': config.get(section, "cleardc").encode('cp1251').decode('utf-8'),
    'rolldc': config.get(section, "rolldc").encode('cp1251').decode('utf-8'),
    'dicedc': config.get(section, "dicedc").encode('cp1251').decode('utf-8'),
    'coindc': config.get(section, "coindc").encode('cp1251').decode('utf-8'),
    'coinheads': config.get(section, "coinheads").encode('cp1251').decode('utf-8'),
    'cointails': config.get(section, "cointails").encode('cp1251').decode('utf-8'),
}